version: '3'

services:
  db:
    container_name: database
    image: mysql:latest
    hostname: 'host'
    command: '--default-authentication-plugin=mysql_native_password'
    restart: unless-stopped
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: 'username'
      MYSQL_PASSWORD: 'secretpassword'
      MYSQL_DATABASE: 'mydb1'
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  new:
    depends_on:
      - db
    container_name: newapp
    restart: unless-stopped
    links:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000  


